#ifndef __GENERIC64_HW_H_
#define __GENERIC64_HW_H_

/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2001.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: generic64_hw.H,v 1.2 2001/10/05 21:49:02 peterson Exp $
 *****************************************************************************/

/*****************************************************************************
 * Module Description: mmu and other parapharnelia of the generic64
 * **************************************************************************/


#endif /* #ifndef __GENERIC64_HW_H_ */
