/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mount.h"

bool_t
xdr_dhandle (XDR *xdrs, dhandle objp)
{
	 register long *buf;

	 if (!xdr_opaque (xdrs, objp, FHSIZE))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dirpath (XDR *xdrs, dirpath *objp)
{
	 register long *buf;

	 if (!xdr_string (xdrs, objp, MNTPATHLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_name (XDR *xdrs, name *objp)
{
	 register long *buf;

	 if (!xdr_string (xdrs, objp, MNTNAMELEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mountlist (XDR *xdrs, mountlist *objp)
{
	 register long *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct mountnode), (xdrproc_t) xdr_mountnode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_grouplist (XDR *xdrs, grouplist *objp)
{
	 register long *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct groupnode), (xdrproc_t) xdr_groupnode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_exportlist (XDR *xdrs, exportlist *objp)
{
	 register long *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct exportnode), (xdrproc_t) xdr_exportnode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mountnode (XDR *xdrs, mountnode *objp)
{
	 register long *buf;

	 if (!xdr_name (xdrs, &objp->hostname))
		 return FALSE;
	 if (!xdr_dirpath (xdrs, &objp->directory))
		 return FALSE;
	 if (!xdr_mountlist (xdrs, &objp->nextentry))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_groupnode (XDR *xdrs, groupnode *objp)
{
	 register long *buf;

	 if (!xdr_name (xdrs, &objp->grname))
		 return FALSE;
	 if (!xdr_grouplist (xdrs, &objp->grnext))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_exportnode (XDR *xdrs, exportnode *objp)
{
	 register long *buf;

	 if (!xdr_dirpath (xdrs, &objp->filesys))
		 return FALSE;
	 if (!xdr_grouplist (xdrs, &objp->groups))
		 return FALSE;
	 if (!xdr_exportlist (xdrs, &objp->next))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_fhstatus (XDR *xdrs, fhstatus *objp)
{
	 register long *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case 0:
		 if (!xdr_dhandle (xdrs, objp->fhstatus_u.directory))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
