# ############################################################################
# K42: (C) Copyright IBM Corp. 2001.
# All Rights Reserved
#
# This file is distributed under the GNU LGPL. You should have
# received a copy of the License along with K42; see the file LICENSE.html
# in the top-level directory for more details.
#
#  $Id: Makefile,v 1.2 2002/03/24 14:52:25 jimix Exp $
# ############################################################################

#
# Path to the kitchsrc directory
#
topsrc=../../../..

#
# SGML file that is the begining of one complete document
#
DOCSRCS=spec.sgml

#
# List of supporting (or secondary) files
#
COMMON= spec.ent specOver.sgml specPrgG.sgml specResults.sgml

include $(topsrc)/doc/Makefile.doc
