#ifndef __FREELIST_H_
#define __FREELIST_H_
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000-2003
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: FreeList.H,v 1.3 2003/08/18 01:40:06 dilma Exp $
 *****************************************************************************/
/*****************************************************************************
 * Module Description: Maintains a per-file system free list
 * **************************************************************************/

class FreeList {
public:
    void init() {  }
};

#endif //__FREELIST_H_
