#ifndef __TIMER_H_
#define __TIMER_H_
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: Timer.H,v 1.6 2001/10/05 21:49:40 peterson Exp $
 *****************************************************************************/
/*****************************************************************************
 * Module Description:
 *    PwrPC specific definition of a timer class
 *    responsible to set the timer counters etc.
 * **************************************************************************/

#include __MINC(Timer.H)

#endif /* #ifndef __TIMER_H_ */
