#ifndef __GENERIC64_MACDEFS_H_
#define __GENERIC64_MACDEFS_H_
/* ****************************************************************************
 * K42: (C) Copyright IBM Corp. 2001.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: macdefs.H,v 1.2 2001/10/05 21:48:41 peterson Exp $
 *************************************************************************** */

#define LOG_PAGE_SIZE 12
#define LOG_MAX_PAGE_SIZE LOG_PAGE_SIZE	// different if multiple page sizes

#define LOG_SEGMENT_SIZE 32
#endif /* #ifndef __GENERIC64_MACDEFS_H_ */
