# ############################################################################
# K42: (C) Copyright IBM Corp. 2000.
# All Rights Reserved
#
# This file is distributed under the GNU LGPL. You should have
# received a copy of the License along with K42; see the file LICENSE.html
# in the top-level directory for more details.
#
#  $Id: Makefile,v 1.100 2002/10/03 02:31:46 mostrows Exp $
# ############################################################################

default:: libobjs

SUBDIRS =  cobj io stdlib alloc misc sys usr scheduler trace sync fslib

-include Make.config
include $(MKKITCHTOP)/lib/Makerules.kitch

