# ############################################################################
# K42: (C) Copyright IBM Corp. 2001.
# All Rights Reserved
#
# This file is distributed under the GNU LGPL. You should have
# received a copy of the License along with K42; see the file LICENSE.html
# in the top-level directory for more details.
#
#  $Id: Makefile,v 1.4 2003/03/10 23:32:05 bob Exp $
# ############################################################################

SUBDIRS = amd64 generic64 powerpc

#
# Path to the kitchsrc directory
#
topsrc=../../../..

#
# SGML file that is the begining of one complete document
#
DOCSRCS=arch.sgml

#
# List of supporting (or secondary) files
#
COMMON= arch.ent archOver.sgml archPrgG.sgml

include $(topsrc)/doc/Makefile.doc
