#ifndef __SYS_FACTS_H_
<<<< include machine independent file - not this machine dependent file >>>>
#endif /* #ifndef __SYS_FACTS_H_ */
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: SysFacts.H,v 1.17 2004/11/12 21:25:46 marc Exp $
 *****************************************************************************/
/*****************************************************************************
 * Module Description: machine specific component of SysFacts.H
 * **************************************************************************/

#ifdef INCLASS
#else /* #ifdef INCLASS */
					// pure methods must be outside of
					// class but in .H so each compile sees
					// them. .H is included twice by

#endif /* #ifdef INCLASS */
