#ifndef __BLOCK_H_
<<<< include machine independant file - not this machine dependent file >>>>
#endif /* #ifndef __BLOCK_H_ */
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2001.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: BLock.H,v 1.2 2001/10/05 21:48:26 peterson Exp $
 *****************************************************************************/
/*****************************************************************************
 * Module Description: Blocking locks, this is the standard locking
 * type included everywhere.
 * **************************************************************************/

#include <sync/BLockGeneric.H>
