#ifndef __TRACE_INCS_H_
#define __TRACE_INCS_H_
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: traceIncs.H,v 1.28 2005/08/22 14:10:07 dilma Exp $
 *****************************************************************************/
/*****************************************************************************
 * Module Description: a file to include all of the trace files
 * **************************************************************************/

#include <trace/traceDefault.h>
#include <trace/traceTest.h>
#include <trace/traceMem.h>
#include <trace/traceLock.h>
#include <trace/traceUser.h>
#include <trace/traceIO.h>
#include <trace/traceAlloc.h>
#include <trace/traceMisc.h>
#include <trace/traceProc.h>
#include <trace/traceMiscKern.h>
#include <trace/traceClustObj.h>
#include <trace/traceException.h>
#include <trace/traceScheduler.h>
#include <trace/traceDbg.h>
#include <trace/traceFS.h>
#include <trace/traceDisk.h>
#include <trace/traceLinux.h>
#include <trace/traceControl.h>
#include <trace/traceHWPerfMon.h>
#include <trace/traceSwap.h>
#include <trace/traceResMgr.h>
#include <trace/traceApp.h>
#include <trace/traceOMP.h>
#include <trace/traceInfo.h>
#include <trace/traceLibC.h>
#include <trace/traceMPI.h>

#endif /* #ifndef __TRACE_INCS_H_ */
