#ifndef __TRACE_H_
#define __TRACE_H_
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: trace.H,v 1.64 2003/01/13 19:23:32 rosnbrg Exp $
 *****************************************************************************/
/*****************************************************************************
 * Module Description: definitions for tracing facility
 * **************************************************************************/

#include <sys/KernelInfo.H>
// KernelInfo.H includes traceCore.H

#endif /* #ifndef __TRACE_H_ */
