# ############################################################################
# K42: (C) Copyright IBM Corp. 2002.
# All Rights Reserved
#
# This file is distributed under the GNU LGPL. You should have
# received a copy of the License along with K42; see the file LICENSE.html
# in the top-level directory for more details.
#
# ############################################################################

#
# Path to the kitchsrc directory
#
topsrc=../../../..

#
# SGML file that is the begining of one complete document
#
DOCSRCS=virtfs.sgml

#
# List of supporting (or secondary) files
#
COMMON= virtfs.ent virtfsOver.sgml virtfsPrgG.sgml

include $(topsrc)/doc/Makefile.doc
