# ############################################################################
# K42: (C) Copyright IBM Corp. 2000.
# All Rights Reserved
#
# This file is distributed under the GNU LGPL. You should have
# received a copy of the License along with K42; see the file LICENSE.html
# in the top-level directory for more details.
#
#  $Id: Makefile,v 1.2 2002/06/10 15:46:31 mostrows Exp $
# ############################################################################
# nothing to be done here, part of baseServers
.SUFFIXES:
.DEFAULT:
	-(cd ../baseServers/ && $(MAKE) $@)

.PHONY: default
default:
	-(cd ../baseServers/ && $(MAKE))

