#ifndef __OBJ_TOKEN_H_
#define __OBJ_TOKEN_H_

/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000, 2003.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * Some corrections by Livio Soares (livio@ime.usp.br)
 *
 * $Id: ObjToken.H,v 1.3 2004/05/05 19:57:59 lbsoares Exp $
 *****************************************************************************/
/******************************************************************************
 *
 *		  Hurricane File Manager : ObjectToken.h
 *			     Copyright 1989
 *
 *		 Authors: Orran Krieger
 *****************************************************************************/

struct ObjTokenID {
    uval64 id;
};

#endif /* #ifndef __OBJ_TOKEN_H_ */
