#ifndef __DEBUG_SOFT_INTRS_H_
#define __DEBUG_SOFT_INTRS_H_
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: debug_soft_intrs.H,v 1.2 2001/10/05 21:49:22 peterson Exp $
 *****************************************************************************/
/*****************************************************************************
 * Module Description: defines flag which enables debugging of soft-interrupt
 *                     generation and consumption.
 * **************************************************************************/

//#define DEBUG_SOFT_INTERRUPTS

#endif /* #ifndef __DEBUG_SOFT_INTRS_H_ */
