#ifndef __LINUX_SUPPORT_H_
#define __LINUX_SUPPORT_H_
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: linux_support.H,v 1.2 2001/10/05 21:49:23 peterson Exp $
 *****************************************************************************/
/*****************************************************************************
 * Module Description: Controls linux support on K42.
 * **************************************************************************/
#define __NO_LINUX_IMPL_WARNINGS
#endif /* #ifndef __LINUX_SUPPORT_H_ */
