#ifndef __OPTIMIZATIONS_H_
#define __OPTIMIZATIONS_H_
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: optimizations.H,v 1.14 2003/03/21 15:09:17 rosnbrg Exp $
 *****************************************************************************/
/*****************************************************************************
 * Module Description: defines varios flags which drive optimizations done
 * for performance measurements.
 * **************************************************************************/

#define PAD_FAULT_NOTIFICATION		// FaultNotificationMgr.H
#define PAD_HATDEFAULT

#endif /* #ifndef __OPTIMIZATIONS_H_ */
