#ifndef __PGFLT_STATS_H_
#define __PGFLT_STATS_H_
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2002.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: pgflt_stats.H,v 1.2 2003/02/28 15:44:21 mostrows Exp $
 *****************************************************************************/
/*****************************************************************************
 * Module Description: defines flag which enables statistics collection for
 *                     page faults.
 * **************************************************************************/

//#define COLLECT_FAULT_STATS
//#define MEMOP_TIMERS

#endif /* #ifndef __PGFLT_STATS_H_ */
