#ifndef __SIM_BUGS_H_
#define __SIM_BUGS_H_
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: sim_bugs.H,v 1.12 2003/08/28 18:46:26 okrieg Exp $
 *****************************************************************************/
/*****************************************************************************
 * Module Description: defines varios flags which drive workarounds
 * for simulators we are currently using
 * **************************************************************************/

// do a fast regression test with minimal dependancies on simulator, i.e.,
// no simip...
// #define FAST_REGRESS_ON_SIM		

#endif /* #ifndef __SIM_BUGS_H_ */
