#! /usr/bin/env bash
#/*****************************************************************************
# * K42: (C) Copyright IBM Corp. 2001.
# * All Rights Reserved
# *
# * This file is distributed under the GNU LGPL. You should have
# * received a copy of the license along with K42; see the file LICENSE.html
# * in the top-level directory for more details.
# *
# ****************************************************************************/
#/****************************************************************************
# * Module Description: System initialization script
# * **************************************************************************/

#
# Gather traces for radix
#
# CONSTRAINTS:
#   If statusFile does not exist, start from the beginning.
#
# @author Peter F. Sweeney
# @date   1/3/2005

command=./pemRunRadix.sh
size=-large

sampleRate="-sampleRate 1000000"

# files
   statusFile="/home/pem/.radix"
     modeFile="/home/pem/.radix.mode"
extensionFile="/home/pem/.radix.extension"

#set up environment
/kbin/sysinit

if [[ ! -a $statusFile ]]; then 
    echo "CPO: start call /kbin/sysinit"
    echo 0 > $statusFile
#    echo "0|X 1" > /ksys/console
fi

cd /apps/radix
     MODE=`cat $modeFile`
   STATUS=`cat $statusFile`
EXTENSION=`cat $extensionFile`

echo "Gathering CPO/PEM radix traces mode $MODE status $STATUS extension $EXTENSION"

if [[ $STATUS == 0 ]]; then 
    echo "CPO: 0 $command -pmu -lp000 $sampleRate $MODE -f $EXTENSION $size"
    echo 1 > $statusFile
    $command -pmu -lp000 $sampleRate $MODE -f $EXTENSION $size
    echo "T|I" > /ksys/console
    echo "0|X 1" > /ksys/console
fi

if [[ $STATUS == 1 ]]; then 
    echo "CPO: 1 $command -pmu -lp100 $sampleRate $MODE -f $EXTENSION $size"
    echo 2 > $statusFile
    $command -pmu -lp100 $sampleRate $MODE -f $EXTENSION $size
    echo "T|I" > /ksys/console
    echo "0|X 1" > /ksys/console
fi

if [[ $STATUS == 2 ]]; then 
    echo "CPO: 2 $command -pmu -lp010 $sampleRate $MODE -f $EXTENSION  $size"
    echo 3 > $statusFile
    $command -pmu -lp010 $sampleRate $MODE -f $EXTENSION  $size
    echo "T|I" > /ksys/console
    echo "0|X 1" > /ksys/console
fi

if [[ $STATUS == 3 ]]; then 
    echo "CPO: 3 $command -pmu -lp001 $sampleRate $MODE -f $EXTENSION  $size"
    echo 4 > $statusFile
    $command -pmu -lp001 $sampleRate $MODE -f $EXTENSION  $size
    echo "T|I" > /ksys/console
    echo "0|X 1" > /ksys/console
fi

if [[ $STATUS == 4 ]]; then 
    echo "CPO: 4 $command -pmu -lp110 $sampleRate $MODE -f $EXTENSION  $size"
    echo 5 > $statusFile
    $command -pmu -lp110 $sampleRate $MODE -f $EXTENSION  $size
    echo "T|I" > /ksys/console
    echo "0|X 1" > /ksys/console
fi

if [[ $STATUS == 5 ]]; then 
    echo "CPO: 5 $command -pmu -lp101 $sampleRate $MODE -f $EXTENSION  $size"
    echo 6 > $statusFile
    $command -pmu -lp101 $sampleRate $MODE -f $EXTENSION  $size
    echo "T|I" > /ksys/console
    echo "0|X 1" > /ksys/console
fi

if [[ $STATUS == 6 ]]; then 
    echo "CPO: 6 $command -pmu -lp011 $sampleRate $MODE -f $EXTENSION  $size"
    echo 7 > $statusFile
    $command -pmu -lp011 $sampleRate $MODE -f $EXTENSION  $size
    echo "T|I" > /ksys/console
    echo "0|X 1" > /ksys/console
fi

if [[ $STATUS == 7 ]]; then 
    echo "CPO: 7 $command -pmu -lp111 $sampleRate $MODE -f $EXTENSION  $size"
    echo 8 > $statusFile
    $command -pmu -lp111 $sampleRate $MODE -f $EXTENSION  $size
    echo "T|I" > /ksys/console
    echo "0|X 1" > /ksys/console
fi

dataSampleRate=1000
if [[ $STATUS == 8 ]]; then 
    echo "CPO: 8 $command -pmu -data $dataSampleRate $MODE -f $EXTENSION  $size"
    echo 9 > $statusFile
    $command -pmu -data $dataSampleRate $MODE -f $EXTENSION  $size
    echo "T|I" > /ksys/console
    echo "0|X 1" > /ksys/console
fi

dataSampleRate=500
if [[ $STATUS == 9 ]]; then 
    echo "CPO: 9 $command -pmu -data $dataSampleRate $MODE -f $EXTENSION  $size"
    echo 10 > $statusFile
    $command -pmu -data $dataSampleRate $MODE -f $EXTENSION  $size
    echo "T|I" > /ksys/console
    echo "0|X 1" > /ksys/console
fi

dataSampleRate=100
if [[ $STATUS == 10 ]]; then 
    echo "CPO: 10 $command -pmu -data $dataSampleRate $MODE -f $EXTENSION  $size"
    echo 11 > $statusFile
    $command -pmu -data $dataSampleRate $MODE -f $EXTENSION  $size
    echo "T|I" > /ksys/console
    echo "0|X 1" > /ksys/console
fi

dataSampleRate=50
if [[ $STATUS == 11 ]]; then 
    echo "CPO: 11 $command -pmu -data $dataSampleRate $MODE -f $EXTENSION  $size"
    echo 12 > $statusFile
    $command -pmu -data $dataSampleRate $MODE -f $EXTENSION  $size
    echo "T|I" > /ksys/console
    echo "0|X 1" > /ksys/console
fi

echo "CPO: ending  rm $statusFile"
rm $statusFile
echo "0|XX" > /ksys/console
