#! /usr/bin/env bash
 
#/*****************************************************************************
# * K42: (C) Copyright IBM Corp. 2001.
# * All Rights Reserved
# *
# * This file is distributed under the GNU LGPL. You should have
# * received a copy of the license along with K42; see the file LICENSE.html
# * in the top-level directory for more details.
# *
# ****************************************************************************/
# $Id: regression,v 1.8 2005/03/09 17:11:35 pfs Exp $
#
# Automatically generate PEM traces for benchmarks
# Approach for CFP
#   loop over benchmarks
#   call regression-SPECcpu for each benchmark
#
# Must have set up the path correctly before executing: k42_paths
#
# @author Peter F. Sweeney
# @date   1/8/2004


if [[ -z $K42_TOP ]]; then
  echo ""
  echo "***Must set K42_TOP to point to your version of k42!***"
  exit -1
fi
echo "where \"`where k42console`\""
if [[ ! -n `where k42console` ]]; then
  echo ""
  echo "***Path is not set up correctly to find k42console!***"
  echo "path: $path"
  exit -1
fi

export K42_TRACE_LOG_NUMB_BUFS=8
export K42_NUMB_LARGE_PAGES_RESERVED=40

# training inputs
#machine=kxs1

# reference inputs
machine=kxs2

echo ""
echo "Environment variables:"
printenv | grep K42

set -x

#############
#run SPECfp

benchFp="Swim Mgrid Applu Mesa Galgel Art Equake Facerec Ammp Lucas Fma3d Sixtrack Wupwise Apsi"
benchFp="Art Equake Sixtrack Apsi"

for benchmark in $benchFp 
do
    echo "regression calls ./regression-SPECcpu $machine $benchmark"
    ./regression-SPECcpu $machine $benchmark
done

exit -l


##############
# run SPECint

benchInt="Gzip Vpr Mcf Crafty Parser Eon Perlbmk Gap Vortex Bzip2 Twolf"

for benchmark in $benchInt 
do
    echo "./regression-SPECcpu INT $machine $benchmark"
    ./regression-SPECcpu $machine $benchmark
done



./regression-radix $machine

./regression-cth $machine

./regression-sweep3d $machine

./regression-umt2k $machine


