#ifndef __SYSCALLS_H_
#define __SYSCALLS_H_
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: syscalls.H,v 1.7 2001/10/05 21:50:21 peterson Exp $
 *****************************************************************************/
/*****************************************************************************
 * Module Description: Defines the basic system call vector
 * **************************************************************************/

#include __MINC(syscalls.H)

#endif /* #ifndef __SYSCALLS_H_ */
