#ifndef __VOLATILE_STATE_H_
#define __VOLATILE_STATE_H_
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: VolatileState.H,v 1.5 2001/10/05 21:50:21 peterson Exp $
 *****************************************************************************/
/*****************************************************************************
 * Module Description:
 * **************************************************************************/

#include __MINC(VolatileState.H)
#endif /* #ifndef __VOLATILE_STATE_H_ */
