# ############################################################################
# K42: (C) Copyright IBM Corp. 2001.
# All Rights Reserved
#
# This file is distributed under the GNU LGPL. You should have
# received a copy of the License along with K42; see the file LICENSE.html
# in the top-level directory for more details.
#
#  $Id: Makefile,v 1.3 2001/10/18 15:08:08 bob Exp $
# ############################################################################

#
# Path to the kitchsrc directory
#
topsrc=../../../../..

#
# SGML file that is the begining of one complete document
#
DOCSRCS=powerpc.sgml

#
# List of supporting (or secondary) files
#
COMMON= powerpc.ent powerpcOver.sgml powerpcPrgG.sgml

include $(topsrc)/doc/Makefile.doc
