#ifdef __LK_KERN_INCS_H_
#error <lkKernIncs.H> should be included once from every bilge/linux .C file.
#else
#define __LK_KERN_INCS_H_
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2001, 2002.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: lkKernIncs.H,v 1.1 2004/02/27 17:14:22 mostrows Exp $
 *****************************************************************************/

#include <lk/fixup.H>
#include <kernIncs.H>


#endif /* #ifndef __LK_KERN_INCS_H_ */
