#ifndef __COSDEFAULT_OBJECT_H_
#define __COSDEFAULT_OBJECT_H_
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: COSDefaultObject.H,v 1.7 2001/10/05 21:47:25 peterson Exp $
 *****************************************************************************/
/******************************************************************************
 * This file is derived from Tornado software developed at the University
 * of Toronto.
 *****************************************************************************/
/*****************************************************************************
 * Module Description:
 * **************************************************************************/
#include "COSTransObject.H"

class COSDefaultObject : public COSTransObject {
public:
    virtual SysStatus method1()   {return -1;}
    virtual SysStatus method2()   {return -1;}
    virtual SysStatus method3()   {return -1;}
    virtual SysStatus method4()   {return -1;}
    virtual SysStatus method5()   {return -1;}
    virtual SysStatus method6()   {return -1;}
    virtual SysStatus method7()   {return -1;}
    virtual SysStatus method8()   {return -1;}
    virtual SysStatus method9()   {return -1;}
    virtual SysStatus method10()  {return -1;}

    virtual SysStatus method11()  {return -1;}
    virtual SysStatus method12()  {return -1;}
    virtual SysStatus method13()  {return -1;}
    virtual SysStatus method14()  {return -1;}
    virtual SysStatus method15()  {return -1;}
    virtual SysStatus method16()  {return -1;}
    virtual SysStatus method17()  {return -1;}
    virtual SysStatus method18()  {return -1;}
    virtual SysStatus method19()  {return -1;}

    virtual SysStatus method20()  {return -1;}
    virtual SysStatus method21()  {return -1;}
    virtual SysStatus method22()  {return -1;}
    virtual SysStatus method23()  {return -1;}
    virtual SysStatus method24()  {return -1;}
    virtual SysStatus method25()  {return -1;}
    virtual SysStatus method26()  {return -1;}
    virtual SysStatus method27()  {return -1;}
    virtual SysStatus method28()  {return -1;}
    virtual SysStatus method29()  {return -1;}

    virtual SysStatus method30()  {return -1;}
    virtual SysStatus method31()  {return -1;}
    virtual SysStatus method32()  {return -1;}
    virtual SysStatus method33()  {return -1;}
    virtual SysStatus method34()  {return -1;}
    virtual SysStatus method35()  {return -1;}
    virtual SysStatus method36()  {return -1;}
    virtual SysStatus method37()  {return -1;}
    virtual SysStatus method38()  {return -1;}
    virtual SysStatus method39()  {return -1;}

    virtual SysStatus method40()  {return -1;}
    virtual SysStatus method41()  {return -1;}
    virtual SysStatus method42()  {return -1;}
    virtual SysStatus method43()  {return -1;}
    virtual SysStatus method44()  {return -1;}
    virtual SysStatus method45()  {return -1;}
    virtual SysStatus method46()  {return -1;}
    virtual SysStatus method47()  {return -1;}
    virtual SysStatus method48()  {return -1;}
    virtual SysStatus method49()  {return -1;}

    virtual SysStatus method50()  {return -1;}
    virtual SysStatus method51()  {return -1;}
    virtual SysStatus method52()  {return -1;}
    virtual SysStatus method53()  {return -1;}
    virtual SysStatus method54()  {return -1;}
    virtual SysStatus method55()  {return -1;}
    virtual SysStatus method56()  {return -1;}
    virtual SysStatus method57()  {return -1;}
    virtual SysStatus method58()  {return -1;}
    virtual SysStatus method59()  {return -1;}

    virtual SysStatus method60()  {return -1;}
    virtual SysStatus method61()  {return -1;}
    virtual SysStatus method62()  {return -1;}
    virtual SysStatus method63()  {return -1;}
    virtual SysStatus method64()  {return -1;}
    virtual SysStatus method65()  {return -1;}
    virtual SysStatus method66()  {return -1;}
    virtual SysStatus method67()  {return -1;}
    virtual SysStatus method68()  {return -1;}
    virtual SysStatus method69()  {return -1;}

    virtual SysStatus method70()  {return -1;}
    virtual SysStatus method71()  {return -1;}
    virtual SysStatus method72()  {return -1;}
    virtual SysStatus method73()  {return -1;}
    virtual SysStatus method74()  {return -1;}
    virtual SysStatus method75()  {return -1;}
    virtual SysStatus method76()  {return -1;}
    virtual SysStatus method77()  {return -1;}
    virtual SysStatus method78()  {return -1;}
    virtual SysStatus method79()  {return -1;}

    virtual SysStatus method80()  {return -1;}
    virtual SysStatus method81()  {return -1;}
    virtual SysStatus method82()  {return -1;}
    virtual SysStatus method83()  {return -1;}
    virtual SysStatus method84()  {return -1;}
    virtual SysStatus method85()  {return -1;}
    virtual SysStatus method86()  {return -1;}
    virtual SysStatus method87()  {return -1;}
    virtual SysStatus method88()  {return -1;}
    virtual SysStatus method89()  {return -1;}

    virtual SysStatus method90()  {return -1;}
    virtual SysStatus method91()  {return -1;}
    virtual SysStatus method92()  {return -1;}
    virtual SysStatus method93()  {return -1;}
    virtual SysStatus method94()  {return -1;}
    virtual SysStatus method95()  {return -1;}
    virtual SysStatus method96()  {return -1;}
    virtual SysStatus method97()  {return -1;}
    virtual SysStatus method98()  {return -1;}
    virtual SysStatus method99()  {return -1;}

    virtual SysStatus method100()   {return -1;}
    virtual SysStatus method101()   {return -1;}
    virtual SysStatus method102()   {return -1;}
    virtual SysStatus method103()   {return -1;}
    virtual SysStatus method104()   {return -1;}
    virtual SysStatus method105()   {return -1;}
    virtual SysStatus method106()   {return -1;}
    virtual SysStatus method107()   {return -1;}
    virtual SysStatus method108()   {return -1;}
    virtual SysStatus method109()  {return -1;}

    virtual SysStatus method110()  {return -1;}
    virtual SysStatus method111()  {return -1;}
    virtual SysStatus method112()  {return -1;}
    virtual SysStatus method113()  {return -1;}
    virtual SysStatus method114()  {return -1;}
    virtual SysStatus method115()  {return -1;}
    virtual SysStatus method116()  {return -1;}
    virtual SysStatus method117()  {return -1;}
    virtual SysStatus method118()  {return -1;}
    virtual SysStatus method119()  {return -1;}

    virtual SysStatus method120()  {return -1;}
    virtual SysStatus method121()  {return -1;}
    virtual SysStatus method122()  {return -1;}
    virtual SysStatus method123()  {return -1;}
    virtual SysStatus method124()  {return -1;}
    virtual SysStatus method125()  {return -1;}
    virtual SysStatus method126()  {return -1;}
    virtual SysStatus method127()  {return -1;}
    virtual SysStatus method128()  {return -1;}
    virtual SysStatus method129()  {return -1;}

    virtual SysStatus method130()  {return -1;}
    virtual SysStatus method131()  {return -1;}
    virtual SysStatus method132()  {return -1;}
    virtual SysStatus method133()  {return -1;}
    virtual SysStatus method134()  {return -1;}
    virtual SysStatus method135()  {return -1;}
    virtual SysStatus method136()  {return -1;}
    virtual SysStatus method137()  {return -1;}
    virtual SysStatus method138()  {return -1;}
    virtual SysStatus method139()  {return -1;}

    virtual SysStatus method140()  {return -1;}
    virtual SysStatus method141()  {return -1;}
    virtual SysStatus method142()  {return -1;}
    virtual SysStatus method143()  {return -1;}
    virtual SysStatus method144()  {return -1;}
    virtual SysStatus method145()  {return -1;}
    virtual SysStatus method146()  {return -1;}
    virtual SysStatus method147()  {return -1;}
    virtual SysStatus method148()  {return -1;}
    virtual SysStatus method149()  {return -1;}

    virtual SysStatus method150()  {return -1;}
    virtual SysStatus method151()  {return -1;}
    virtual SysStatus method152()  {return -1;}
    virtual SysStatus method153()  {return -1;}
    virtual SysStatus method154()  {return -1;}
    virtual SysStatus method155()  {return -1;}
    virtual SysStatus method156()  {return -1;}
    virtual SysStatus method157()  {return -1;}
    virtual SysStatus method158()  {return -1;}
    virtual SysStatus method159()  {return -1;}

    virtual SysStatus method160()  {return -1;}
    virtual SysStatus method161()  {return -1;}
    virtual SysStatus method162()  {return -1;}
    virtual SysStatus method163()  {return -1;}
    virtual SysStatus method164()  {return -1;}
    virtual SysStatus method165()  {return -1;}
    virtual SysStatus method166()  {return -1;}
    virtual SysStatus method167()  {return -1;}
    virtual SysStatus method168()  {return -1;}
    virtual SysStatus method169()  {return -1;}

    virtual SysStatus method170()  {return -1;}
    virtual SysStatus method171()  {return -1;}
    virtual SysStatus method172()  {return -1;}
    virtual SysStatus method173()  {return -1;}
    virtual SysStatus method174()  {return -1;}
    virtual SysStatus method175()  {return -1;}
    virtual SysStatus method176()  {return -1;}
    virtual SysStatus method177()  {return -1;}
    virtual SysStatus method178()  {return -1;}
    virtual SysStatus method179()  {return -1;}

    virtual SysStatus method180()  {return -1;}
    virtual SysStatus method181()  {return -1;}
    virtual SysStatus method182()  {return -1;}
    virtual SysStatus method183()  {return -1;}
    virtual SysStatus method184()  {return -1;}
    virtual SysStatus method185()  {return -1;}
    virtual SysStatus method186()  {return -1;}
    virtual SysStatus method187()  {return -1;}
    virtual SysStatus method188()  {return -1;}
    virtual SysStatus method189()  {return -1;}

    virtual SysStatus method190()  {return -1;}
    virtual SysStatus method191()  {return -1;}
    virtual SysStatus method192()  {return -1;}
    virtual SysStatus method193()  {return -1;}
    virtual SysStatus method194()  {return -1;}
    virtual SysStatus method195()  {return -1;}
    virtual SysStatus method196()  {return -1;}
    virtual SysStatus method197()  {return -1;}
    virtual SysStatus method198()  {return -1;}
    virtual SysStatus method199()  {return -1;}

    virtual SysStatus method200()   {return -1;}
    virtual SysStatus method201()   {return -1;}
    virtual SysStatus method202()   {return -1;}
    virtual SysStatus method203()   {return -1;}
    virtual SysStatus method204()   {return -1;}
    virtual SysStatus method205()   {return -1;}
    virtual SysStatus method206()   {return -1;}
    virtual SysStatus method207()   {return -1;}
    virtual SysStatus method208()   {return -1;}
    virtual SysStatus method209()  {return -1;}

    virtual SysStatus method210()  {return -1;}
    virtual SysStatus method211()  {return -1;}
    virtual SysStatus method212()  {return -1;}
    virtual SysStatus method213()  {return -1;}
    virtual SysStatus method214()  {return -1;}
    virtual SysStatus method215()  {return -1;}
    virtual SysStatus method216()  {return -1;}
    virtual SysStatus method217()  {return -1;}
    virtual SysStatus method218()  {return -1;}
    virtual SysStatus method219()  {return -1;}

    virtual SysStatus method220()  {return -1;}
    virtual SysStatus method221()  {return -1;}
    virtual SysStatus method222()  {return -1;}
    virtual SysStatus method223()  {return -1;}
    virtual SysStatus method224()  {return -1;}
    virtual SysStatus method225()  {return -1;}
    virtual SysStatus method226()  {return -1;}
    virtual SysStatus method227()  {return -1;}
    virtual SysStatus method228()  {return -1;}
    virtual SysStatus method229()  {return -1;}

    virtual SysStatus method230()  {return -1;}
    virtual SysStatus method231()  {return -1;}
    virtual SysStatus method232()  {return -1;}
    virtual SysStatus method233()  {return -1;}
    virtual SysStatus method234()  {return -1;}
    virtual SysStatus method235()  {return -1;}
    virtual SysStatus method236()  {return -1;}
    virtual SysStatus method237()  {return -1;}
    virtual SysStatus method238()  {return -1;}
    virtual SysStatus method239()  {return -1;}

    virtual SysStatus method240()  {return -1;}
    virtual SysStatus method241()  {return -1;}
    virtual SysStatus method242()  {return -1;}
    virtual SysStatus method243()  {return -1;}
    virtual SysStatus method244()  {return -1;}
    virtual SysStatus method245()  {return -1;}
    virtual SysStatus method246()  {return -1;}
    virtual SysStatus method247()  {return -1;}
    virtual SysStatus method248()  {return -1;}
    virtual SysStatus method249()  {return -1;}

    virtual SysStatus method250()  {return -1;}
    virtual SysStatus method251()  {return -1;}
    virtual SysStatus method252()  {return -1;}
    virtual SysStatus method253()  {return -1;}
    virtual SysStatus method254()  {return -1;}
    virtual SysStatus method255()  {return -1;}

    COSDefaultObject() { init(); }
protected:
    SysStatus init();
};



#endif /* #ifndef __COSDEFAULT_OBJECT_H_ */
