/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: COSDefaultObject.C,v 1.7 2002/09/08 23:10:54 mostrows Exp $
 *****************************************************************************/
/******************************************************************************
 * This file is derived from Tornado software developed at the University
 * of Toronto.
 *****************************************************************************/

#include <sys/sysIncs.H>

#include "COSDefaultObject.H"
#include "COVTable.H"
#include "defaultFuncs.H"

char __missVTable[sizeof(COVTable)] = {0,};
COVTable * const MissVTable = (COVTable*)__missVTable;

//#define SET_DEFAULT_FUNC(OP)
// vtable->vt[OP].setFunc((uval)&defaultFunc ## OP )
#define SET_DEFAULT_FUNC(OP) \
 MissVTable->vt[OP].setFunc((uval)&defaultFunc ## OP )

SysStatus
COSDefaultObject::init()
{
    *(COVTable**)this = MissVTable;
    SET_DEFAULT_FUNC(0); // Not sure we actually want this as the first vtable
                         // seems empty or atleast reserved for other uses,
                         // but for the sake of symmetry
    SET_DEFAULT_FUNC(1);
    SET_DEFAULT_FUNC(2);
    SET_DEFAULT_FUNC(3);
    SET_DEFAULT_FUNC(4);
    SET_DEFAULT_FUNC(5);
    SET_DEFAULT_FUNC(6);
    SET_DEFAULT_FUNC(7);
    SET_DEFAULT_FUNC(8);
    SET_DEFAULT_FUNC(9);

    SET_DEFAULT_FUNC(10);
    SET_DEFAULT_FUNC(11);
    SET_DEFAULT_FUNC(12);
    SET_DEFAULT_FUNC(13);
    SET_DEFAULT_FUNC(14);
    SET_DEFAULT_FUNC(15);
    SET_DEFAULT_FUNC(16);
    SET_DEFAULT_FUNC(17);
    SET_DEFAULT_FUNC(18);
    SET_DEFAULT_FUNC(19);

    SET_DEFAULT_FUNC(20);
    SET_DEFAULT_FUNC(21);
    SET_DEFAULT_FUNC(22);
    SET_DEFAULT_FUNC(23);
    SET_DEFAULT_FUNC(24);
    SET_DEFAULT_FUNC(25);
    SET_DEFAULT_FUNC(26);
    SET_DEFAULT_FUNC(27);
    SET_DEFAULT_FUNC(28);
    SET_DEFAULT_FUNC(29);

    SET_DEFAULT_FUNC(30);
    SET_DEFAULT_FUNC(31);
    SET_DEFAULT_FUNC(32);
    SET_DEFAULT_FUNC(33);
    SET_DEFAULT_FUNC(34);
    SET_DEFAULT_FUNC(35);
    SET_DEFAULT_FUNC(36);
    SET_DEFAULT_FUNC(37);
    SET_DEFAULT_FUNC(38);
    SET_DEFAULT_FUNC(39);

    SET_DEFAULT_FUNC(40);
    SET_DEFAULT_FUNC(41);
    SET_DEFAULT_FUNC(42);
    SET_DEFAULT_FUNC(43);
    SET_DEFAULT_FUNC(44);
    SET_DEFAULT_FUNC(45);
    SET_DEFAULT_FUNC(46);
    SET_DEFAULT_FUNC(47);
    SET_DEFAULT_FUNC(48);
    SET_DEFAULT_FUNC(49);

    SET_DEFAULT_FUNC(50);
    SET_DEFAULT_FUNC(51);
    SET_DEFAULT_FUNC(52);
    SET_DEFAULT_FUNC(53);
    SET_DEFAULT_FUNC(54);
    SET_DEFAULT_FUNC(55);
    SET_DEFAULT_FUNC(56);
    SET_DEFAULT_FUNC(57);
    SET_DEFAULT_FUNC(58);
    SET_DEFAULT_FUNC(59);

    SET_DEFAULT_FUNC(60);
    SET_DEFAULT_FUNC(61);
    SET_DEFAULT_FUNC(62);
    SET_DEFAULT_FUNC(63);
    SET_DEFAULT_FUNC(64);
    SET_DEFAULT_FUNC(65);
    SET_DEFAULT_FUNC(66);
    SET_DEFAULT_FUNC(67);
    SET_DEFAULT_FUNC(68);
    SET_DEFAULT_FUNC(69);

    SET_DEFAULT_FUNC(70);
    SET_DEFAULT_FUNC(71);
    SET_DEFAULT_FUNC(72);
    SET_DEFAULT_FUNC(73);
    SET_DEFAULT_FUNC(74);
    SET_DEFAULT_FUNC(75);
    SET_DEFAULT_FUNC(76);
    SET_DEFAULT_FUNC(77);
    SET_DEFAULT_FUNC(78);
    SET_DEFAULT_FUNC(79);

    SET_DEFAULT_FUNC(80);
    SET_DEFAULT_FUNC(81);
    SET_DEFAULT_FUNC(82);
    SET_DEFAULT_FUNC(83);
    SET_DEFAULT_FUNC(84);
    SET_DEFAULT_FUNC(85);
    SET_DEFAULT_FUNC(86);
    SET_DEFAULT_FUNC(87);
    SET_DEFAULT_FUNC(88);
    SET_DEFAULT_FUNC(89);

    SET_DEFAULT_FUNC(90);
    SET_DEFAULT_FUNC(91);
    SET_DEFAULT_FUNC(92);
    SET_DEFAULT_FUNC(93);
    SET_DEFAULT_FUNC(94);
    SET_DEFAULT_FUNC(95);
    SET_DEFAULT_FUNC(96);
    SET_DEFAULT_FUNC(97);
    SET_DEFAULT_FUNC(98);
    SET_DEFAULT_FUNC(99);

    SET_DEFAULT_FUNC(100);
    SET_DEFAULT_FUNC(101);
    SET_DEFAULT_FUNC(102);
    SET_DEFAULT_FUNC(103);
    SET_DEFAULT_FUNC(104);
    SET_DEFAULT_FUNC(105);
    SET_DEFAULT_FUNC(106);
    SET_DEFAULT_FUNC(107);
    SET_DEFAULT_FUNC(108);
    SET_DEFAULT_FUNC(109);

    SET_DEFAULT_FUNC(110);
    SET_DEFAULT_FUNC(111);
    SET_DEFAULT_FUNC(112);
    SET_DEFAULT_FUNC(113);
    SET_DEFAULT_FUNC(114);
    SET_DEFAULT_FUNC(115);
    SET_DEFAULT_FUNC(116);
    SET_DEFAULT_FUNC(117);
    SET_DEFAULT_FUNC(118);
    SET_DEFAULT_FUNC(119);

    SET_DEFAULT_FUNC(120);
    SET_DEFAULT_FUNC(121);
    SET_DEFAULT_FUNC(122);
    SET_DEFAULT_FUNC(123);
    SET_DEFAULT_FUNC(124);
    SET_DEFAULT_FUNC(125);
    SET_DEFAULT_FUNC(126);
    SET_DEFAULT_FUNC(127);
    SET_DEFAULT_FUNC(128);
    SET_DEFAULT_FUNC(129);

    SET_DEFAULT_FUNC(130);
    SET_DEFAULT_FUNC(131);
    SET_DEFAULT_FUNC(132);
    SET_DEFAULT_FUNC(133);
    SET_DEFAULT_FUNC(134);
    SET_DEFAULT_FUNC(135);
    SET_DEFAULT_FUNC(136);
    SET_DEFAULT_FUNC(137);
    SET_DEFAULT_FUNC(138);
    SET_DEFAULT_FUNC(139);

    SET_DEFAULT_FUNC(140);
    SET_DEFAULT_FUNC(141);
    SET_DEFAULT_FUNC(142);
    SET_DEFAULT_FUNC(143);
    SET_DEFAULT_FUNC(144);
    SET_DEFAULT_FUNC(145);
    SET_DEFAULT_FUNC(146);
    SET_DEFAULT_FUNC(147);
    SET_DEFAULT_FUNC(148);
    SET_DEFAULT_FUNC(149);

    SET_DEFAULT_FUNC(150);
    SET_DEFAULT_FUNC(151);
    SET_DEFAULT_FUNC(152);
    SET_DEFAULT_FUNC(153);
    SET_DEFAULT_FUNC(154);
    SET_DEFAULT_FUNC(155);
    SET_DEFAULT_FUNC(156);
    SET_DEFAULT_FUNC(157);
    SET_DEFAULT_FUNC(158);
    SET_DEFAULT_FUNC(159);

    SET_DEFAULT_FUNC(160);
    SET_DEFAULT_FUNC(161);
    SET_DEFAULT_FUNC(162);
    SET_DEFAULT_FUNC(163);
    SET_DEFAULT_FUNC(164);
    SET_DEFAULT_FUNC(165);
    SET_DEFAULT_FUNC(166);
    SET_DEFAULT_FUNC(167);
    SET_DEFAULT_FUNC(168);
    SET_DEFAULT_FUNC(169);

    SET_DEFAULT_FUNC(170);
    SET_DEFAULT_FUNC(171);
    SET_DEFAULT_FUNC(172);
    SET_DEFAULT_FUNC(173);
    SET_DEFAULT_FUNC(174);
    SET_DEFAULT_FUNC(175);
    SET_DEFAULT_FUNC(176);
    SET_DEFAULT_FUNC(177);
    SET_DEFAULT_FUNC(178);
    SET_DEFAULT_FUNC(179);

    SET_DEFAULT_FUNC(180);
    SET_DEFAULT_FUNC(181);
    SET_DEFAULT_FUNC(182);
    SET_DEFAULT_FUNC(183);
    SET_DEFAULT_FUNC(184);
    SET_DEFAULT_FUNC(185);
    SET_DEFAULT_FUNC(186);
    SET_DEFAULT_FUNC(187);
    SET_DEFAULT_FUNC(188);
    SET_DEFAULT_FUNC(189);

    SET_DEFAULT_FUNC(190);
    SET_DEFAULT_FUNC(191);
    SET_DEFAULT_FUNC(192);
    SET_DEFAULT_FUNC(193);
    SET_DEFAULT_FUNC(194);
    SET_DEFAULT_FUNC(195);
    SET_DEFAULT_FUNC(196);
    SET_DEFAULT_FUNC(197);
    SET_DEFAULT_FUNC(198);
    SET_DEFAULT_FUNC(199);

    SET_DEFAULT_FUNC(200);
    SET_DEFAULT_FUNC(201);
    SET_DEFAULT_FUNC(202);
    SET_DEFAULT_FUNC(203);
    SET_DEFAULT_FUNC(204);
    SET_DEFAULT_FUNC(205);
    SET_DEFAULT_FUNC(206);
    SET_DEFAULT_FUNC(207);
    SET_DEFAULT_FUNC(208);
    SET_DEFAULT_FUNC(209);

    SET_DEFAULT_FUNC(210);
    SET_DEFAULT_FUNC(211);
    SET_DEFAULT_FUNC(212);
    SET_DEFAULT_FUNC(213);
    SET_DEFAULT_FUNC(214);
    SET_DEFAULT_FUNC(215);
    SET_DEFAULT_FUNC(216);
    SET_DEFAULT_FUNC(217);
    SET_DEFAULT_FUNC(218);
    SET_DEFAULT_FUNC(219);

    SET_DEFAULT_FUNC(220);
    SET_DEFAULT_FUNC(221);
    SET_DEFAULT_FUNC(222);
    SET_DEFAULT_FUNC(223);
    SET_DEFAULT_FUNC(224);
    SET_DEFAULT_FUNC(225);
    SET_DEFAULT_FUNC(226);
    SET_DEFAULT_FUNC(227);
    SET_DEFAULT_FUNC(228);
    SET_DEFAULT_FUNC(229);

    SET_DEFAULT_FUNC(230);
    SET_DEFAULT_FUNC(231);
    SET_DEFAULT_FUNC(232);
    SET_DEFAULT_FUNC(233);
    SET_DEFAULT_FUNC(234);
    SET_DEFAULT_FUNC(235);
    SET_DEFAULT_FUNC(236);
    SET_DEFAULT_FUNC(237);
    SET_DEFAULT_FUNC(238);
    SET_DEFAULT_FUNC(239);

    SET_DEFAULT_FUNC(240);
    SET_DEFAULT_FUNC(241);
    SET_DEFAULT_FUNC(242);
    SET_DEFAULT_FUNC(243);
    SET_DEFAULT_FUNC(244);
    SET_DEFAULT_FUNC(245);
    SET_DEFAULT_FUNC(246);
    SET_DEFAULT_FUNC(247);
    SET_DEFAULT_FUNC(248);
    SET_DEFAULT_FUNC(249);

    SET_DEFAULT_FUNC(250);
    SET_DEFAULT_FUNC(251);
    SET_DEFAULT_FUNC(252);
    SET_DEFAULT_FUNC(253);
    SET_DEFAULT_FUNC(254);
    SET_DEFAULT_FUNC(255);
    return 1;
}
