#ifdef __LK_INCS_H_
#error <lk/lkIncs.H> should be included exactly once from every lib/lk .C file.
#else
#define __LK_INCS_H_
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2001, 2002.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: lkIncs.H,v 1.3 2004/02/27 18:10:39 mostrows Exp $
 *****************************************************************************/

#include <lk/fixup.H>
#include <sys/sysIncs.H>

#endif /* #ifndef __LK_INCS_H_ */
