#ifndef	PAGE_ALLOCATOR_KERN_PINNED_DEFH
<<<< include machine independent file - not this machine dependent file >>>>
#endif
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: PageAllocatorKernUnpinned.H,v 1.7 2003/05/06 19:38:20 marc Exp $
 *****************************************************************************/
/*****************************************************************************
 * Module Description: machine-dependent component of unpinned allocator
 * **************************************************************************/
#define SIZE_UNPINNED 		SEGMENT_SIZE
