# ############################################################################
# K42: (C) Copyright IBM Corp. 2001.
# All Rights Reserved
#
# This file is distributed under the GNU LGPL. You should have
# received a copy of the License along with K42; see the file LICENSE.html
# in the top-level directory for more details.
#
#  $Id: Makefile,v 1.3 2004/12/27 13:42:50 dilma Exp $
# ############################################################################

SUBDIRS = kfs nfs pty

#
# Path to the kitchsrc directory
#
topsrc=../../..

#
# SGML file that is the begining of one complete document
#
DOCSRCS=servers.sgml

#
# List of supporting (or secondary) files
#
COMMON= servers.ent servers.sgml servers.sgml

include $(topsrc)/doc/Makefile.doc
