# ############################################################################
# K42: (C) Copyright IBM Corp. 2001.
# All Rights Reserved
#
# This file is distributed under the GNU LGPL. You should have
# received a copy of the License along with K42; see the file LICENSE.html
# in the top-level directory for more details.
#
#  $Id: Makefile,v 1.2 2001/08/23 22:22:25 mike Exp $
# ############################################################################

#
# Path to the kitchsrc directory
#
topsrc=../../../..

#
# SGML file that is the begining of one complete document
#
DOCSRCS=stubtest.sgml

#
# List of supporting (or secondary) files
#
COMMON= stubtest.ent stubtestOver.sgml stubtestPrgG.sgml

include $(topsrc)/doc/Makefile.doc
