#ifndef __ALLOCA_H_
#define __ALLOCA_H_
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: alloca.H,v 1.4 2001/10/05 21:47:51 peterson Exp $
 *****************************************************************************/
/*****************************************************************************
 * Module Description: (possibly) machine-dependent definition of ALLOCA.
 * **************************************************************************/

#include __MINC(alloca.H)

#endif /* #ifndef __ALLOCA_H_ */
