#ifndef __CONFIG_H_
#define __CONFIG_H_
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: config.H,v 1.7 2001/10/05 21:48:36 peterson Exp $
 *****************************************************************************/
/*****************************************************************************
 * Module Description: includes machine specific configuration file
 * that specifies flags for conditional compilation
 * **************************************************************************/
#include __MINC(config.H)

#endif /* #ifndef __CONFIG_H_ */
