# ############################################################################
# K42: (C) Copyright IBM Corp. 2001.
# All Rights Reserved
#
# This file is distributed under the GNU LGPL. You should have
# received a copy of the License along with K42; see the file LICENSE.html
# in the top-level directory for more details.
#
#  $Id: Makefile,v 1.3 2005/06/28 19:43:13 rosnbrg Exp $
# ############################################################################

SUBDIRS = bin etc lib tests users

#
# Path to the kitchsrc directory
#
topsrc=../..

#
# SGML file that is the begining of one complete document
#
DOCSRCS=kitchlinux.sgml

#
# List of supporting (or secondary) files
#
COMMON= kitchlinux.ent kitchlinux.sgml kitchlinux.sgml

include $(topsrc)/doc/Makefile.doc
