#ifndef __CACHE_SYNC_H_
#define __CACHE_SYNC_H_
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: CacheSync.H,v 1.5 2001/10/05 21:49:48 peterson Exp $
 *****************************************************************************/
/*****************************************************************************
 * Module Description: Cache Synchonization
 * **************************************************************************/

#include __MINC(CacheSync.H)
#endif /* #ifndef __CACHE_SYNC_H_ */
