#ifndef __SEGMENT_HATPRIVATE_H_
#define __SEGMENT_HATPRIVATE_H_
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: SegmentHATPrivate.H,v 1.6 2001/10/05 21:50:04 peterson Exp $
 *****************************************************************************/
/*****************************************************************************
 * Module Description:
 * class which defines the hardware dependent paging machanisms
 * **************************************************************************/

#include __MINC(SegmentHATPrivate.H)

#endif /* #ifndef __SEGMENT_HATPRIVATE_H_ */
