#ifndef __SEGMENT_TABLE_H_
#define __SEGMENT_TABLE_H_
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: SegmentTable.H,v 1.7 2001/10/05 21:50:05 peterson Exp $
 *****************************************************************************/
/*****************************************************************************
 * Module Description:
 * **************************************************************************/

#include __MINC(SegmentTable.H)

#endif /* #ifndef __SEGMENT_TABLE_H_ */
