#ifndef __MMU_H_
#define __MMU_H_
/******************************************************************************
 * K42: (C) Copyright IBM Corp. 2000.
 * All Rights Reserved
 *
 * This file is distributed under the GNU LGPL. You should have
 * received a copy of the license along with K42; see the file LICENSE.html
 * in the top-level directory for more details.
 *
 * $Id: mmu.H,v 1.8 2001/10/05 21:49:00 peterson Exp $
 *****************************************************************************/
/*****************************************************************************
 * Module Description: all constants and macros needed to interact with the
 *                     memory management unit.
 * **************************************************************************/


#include __MINC(mmu.H)

#endif /* #ifndef __MMU_H_ */
